
skillMetadata:
  sections:
    - name: Options 
      fields:
        - name: polling_frequency
          type: text
          label: Automatic Polling Frequency in Minutes
          value: "60"
          placeholder: 60
